### ISSUE TITLE
Fabric 1.20.1: v1.4.1 keybind conflict

### ISSUE THREAD

**Issue by ArmandVestibule** [AzureDoom/Wall-Jump#10]
Since updating to v1.4.1 on a Fabric 1.20.1 dedicated server, connected clients are no longer able to use the default cling key (Shift) to cling and leap from walls as described.

If we remove Shift as the binding for Sneak (MC default), Wall Jump works fine.  They simply cannot both be bound to Shift anymore for some reason.

Please advise and let me know if I can provide further information.

Fabric v 0.14.22
MC 1.20.1
Wall-Jump v1.4.1

**Comment by AzureDoom** [comment]
Are you changing the default keybind in the server config at all?

**Comment by ArmandVestibule** [comment]
> Are you changing the default keybind in the server config at all?

No. I have not changed the server config.  Attached for reference (coverted to txt from json).
[walljump.txt](https://github.com/AzureDoom/Wall-Jump/files/12609060/walljump.txt)

**Comment by AzureDoom** [comment]
Please test the latest version.

**Comment by ArmandVestibule** [comment]
Confirmed fixed on our side.  Thank you!
