### ISSUE TITLE
New version missing dependency

### ISSUE THREAD

**Issue by Ultimushadow** [AzureDoom/Wall-Jump#11]
Hey there, I wanted to let you know that the mod currently does not force AzureLib to be installed before the game loads, resulting in a crash. After installing AzureLib though, the game runs just fine and the new config changes are great
While I have the lib on the mind, is there any detriment to running both AzureLib and GeckoLib? I assume mods will either pick one or the other and not have dependencies that would conflict and I didn't have any initial issues running my 300 mod pack but if you have any warnings I would appreciate the heads up!

Crash Report just in case: 
[crash-2023-09-14_00.46.16-client.txt](https://github.com/AzureDoom/Wall-Jump/files/12605235/crash-2023-09-14_00.46.16-client.txt)

**Comment by AzureDoom** [comment]
Ah, I was going to say it's marked as a dep on CurseForge and Modrinth, but you are referring to the mod json file. I will fix it in an update! 

As for AzureLib and Geckolib, no, AzureLib is designed to run just fine in parallel to Geckolib. The fork exists as I was the previous maintainer of Geckolib and was forced out, so I simply forked it into AzureLib to use for my own stuff and to include my own common code into it.

**Comment by Ultimushadow** [comment]
Yep I mistakenly updated but didn't check the pages, I probably could have worded that better lol
Sounds good, I'll close this out since it's not all that important to have open 👍🏻 
Gotcha, thanks for the info!
