### ISSUE TITLE
Network removed functionalities?

### ISSUE THREAD

**Issue by blackshot** [AzureDoom/Wall-Jump#2]
[unnoficial fork](https://www.curseforge.com/minecraft/mc-mods/wall-jump-unofficial-arch) of Wall Jump has a networking removed branch and every [release](https://github.com/dangbroitsdon/Wall-Jump-Unofficial/releases) comes with that version, will this fork have it?

https://github.com/dangbroitsdon/Wall-Jump-Unofficial/tree/1.19-arch-networking-removed

**Comment by AzureDoom** [comment]
This fork will not.
