### ISSUE TITLE
Awesome mod, but needs a toggle

### ISSUE THREAD

**Issue by NopeProsOnly** [AzureDoom/Wall-Jump#3]
I haven't personally used the mod, but there is no mention of a toggle. Without it, I might get flagged by some anticheats.

**Comment by AzureDoom** [comment]
What do you mean by toggle?

**Comment by NopeProsOnly** [comment]
A toggle. Basically something to enable or disable the mod

**Comment by AzureDoom** [comment]
That's not in the scope of this mod, as it's required on both sides. A client-side-only version is not planned.
