### ISSUE TITLE
Client Config Overwrites Server Config

### ISSUE THREAD

**Issue by Ultimushadow** [AzureDoom/Wall-Jump#6]
Hello, I have found that when the mod is installed on a server, the config file is loaded in the server logs but is ignored by the client. Because the mod has some more powerful abilities, I was hoping to allow the enchantments but not the innate player abilities, but anyone joining the server will start with the default config so it won't matter.
I _am_ playing with other mods on the server, but none of them advertise player configs overwriting server configs and this mod is considered server optional on Modrinth, regardless, if this is not typical behavior I will provide the mod list and any other info required.

**Comment by AzureDoom** [comment]
This is fixed with the config update of the 1.20.1 version
