### ISSUE TITLE
Config suggestions

### ISSUE THREAD

**Issue by Ultimushadow** [AzureDoom/Wall-Jump#7]
I was wondering if you could allow manipulation of a couple things
- Max level on Double Jump enchant
- Limited number of Wall Jumps
- If above is implemented, Max level on Wall Jump enchant
- Max level on Speed Boost enchant
- Toggles for each individual enchant
- Ability to change which armor piece the enchants go on (prefer the speed to be on leggings, for instance)
- Re-clinging downwards vs upwards (whereas both are controlled with the same option right now)
- Alter step assist value
- Alter Wall Jump horizontal velocity, not just height
I have seen the code and believe several of these could be quick but helpful additions!

**Comment by AzureDoom** [comment]
Will take a look!

**Comment by Ultimushadow** [comment]
Oh perfect! The server project I was working on ended up taking a huge amount of time so I had hardcoded some of my config preferences into the mod but didn't get to anything too complicated, this will be a huge help since I only altered some numbers 😄

**Comment by AzureDoom** [comment]
> Oh perfect! The server project I was working on ended up taking a huge amount of time so I had hardcoded some of my config preferences into the mod but didn't get to anything too complicated, this will be a huge help since I only altered some numbers 😄

What values did you all change? So far I just have: 
```
Limited number of Wall Jumps
Ability to change which armor piece the enchants go on (prefer the speed to be on leggings, for instance)
Re-clinging downwards vs upwards (whereas both are controlled with the same option right now)
```
That I'm looking at supporting. Rest are in now.

**Comment by Ultimushadow** [comment]
I didn't have a ton of time so I modified the speed boost, double jump value (and I think height?), disabled the wall jump enchantment but kept the other two on, and basically ignore the client config with some hardcoded options. With the update now though I won't have to ignore client config 🙏🏻

**Comment by Ultimushadow** [comment]
Thanks for your work on the mod! I had so much fun testing it out, the movement along with Combat Roll really makes for a more unique experience
